name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ci:
    name: CI
    env:
      POETRY_VERSION: 2.4.1 # renovate: datasource=github-tags depName=python-poetry/poetry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "pyproject.toml"
          cache: poetry
      - run: poetry install
      - run: poetry run pytest tests/ --cov=. --cov-report xml
      - name: Save PR information
        if: github.event_name == 'pull_request'
        run: |
          echo ${{ github.event.number }} > pr-number.txt
          echo ${{ github.event.pull_request.base.ref }} > pr-base.txt
          echo ${{ github.event.pull_request.head.ref }} > pr-head.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ci-artifacts
          path: |
            coverage.xml
            pr-number.txt
            pr-base.txt
            pr-head.txt
